version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

deployment:
  staging:
    branch: haskell-port-heroku-deployment
    heroku:
      appname: slownews-srid
